In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [15]:
v = TfidfVectorizer()
transformed_output = v.fit_transform(corpus)

In [16]:
v.vocabulary_

{'thor': 25,
 'eating': 10,
 'pizza': 22,
 'loki': 17,
 'is': 16,
 'ironman': 15,
 'ate': 7,
 'already': 0,
 'apple': 5,
 'announcing': 4,
 'new': 20,
 'iphone': 14,
 'tomorrow': 26,
 'tesla': 24,
 'model': 19,
 'google': 12,
 'pixel': 21,
 'microsoft': 18,
 'surface': 23,
 'amazon': 2,
 'eco': 11,
 'dot': 9,
 'am': 1,
 'biryani': 8,
 'and': 3,
 'you': 27,
 'are': 6,
 'grapes': 13}

In [17]:
for word in v.get_feature_names_out():
    idx = v.vocabulary_.get(word)
    print(f"{word}  :  {v.idf_[idx]}")

already  :  2.386294361119891
am  :  2.386294361119891
amazon  :  2.386294361119891
and  :  2.386294361119891
announcing  :  1.2876820724517808
apple  :  2.386294361119891
are  :  2.386294361119891
ate  :  2.386294361119891
biryani  :  2.386294361119891
dot  :  2.386294361119891
eating  :  1.9808292530117262
eco  :  2.386294361119891
google  :  2.386294361119891
grapes  :  2.386294361119891
iphone  :  2.386294361119891
ironman  :  2.386294361119891
is  :  1.1335313926245225
loki  :  2.386294361119891
microsoft  :  2.386294361119891
model  :  2.386294361119891
new  :  1.2876820724517808
pixel  :  2.386294361119891
pizza  :  2.386294361119891
surface  :  2.386294361119891
tesla  :  2.386294361119891
thor  :  2.386294361119891
tomorrow  :  1.2876820724517808
you  :  2.386294361119891

In [18]:
transformed_output.toarray()[:2]

array([[0.24266547, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24266547, 0.        , 0.        ,
        0.40286636, 0.        , 0.        , 0.        , 0.        ,
        0.24266547, 0.11527033, 0.24266547, 0.        , 0.        ,
        0.        , 0.        , 0.72799642, 0.        , 0.        ,
        0.24266547, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.30652086,
        0.5680354 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5680354 ,
        0.        , 0.26982671, 0.        , 0.        , 0.        ,
        0.30652086, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30652086, 0.        ]])

In [21]:
import pandas as pd
df = pd.read_csv('tf-idf/Ecommerce_data.csv')
df.head()

                                                Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [22]:
df.label.value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [25]:
df['label_num'] = df.label.map({
    'Household':0,
    'Electronics':1,
    'Clothing & Accessories':2,
    'Books':3,
})

df.head()

,Text,label,label_num
0,Urban Ladder Eisner Low Back Study-Office Comp...,Household,0
1,"Contrast living Wooden Decorative Box,Painted ...",Household,0
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,Electronics,1
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,Clothing & Accessories,2
4,Indira Designer Women's Art Mysore Silk Saree ...,Clothing & Accessories,2

In [28]:
df.isnull().sum()

Text         0
label        0
label_num    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.text,df.label_num)