In [5]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [6]:
wv.similarity(w1='good',w2 = 'great')

np.float32(0.729151)

In [7]:
import pandas as pd
df = pd.read_csv('Fake_Real_Data.csv')
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [9]:
df.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [10]:
df['label_num'] = df['label'].map({
    'Fake':0,
    'Real':1
})
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [29]:
import spacy
nlp = spacy.load('en_core_web_sm')
def preprocess(text):
    doc = nlp(text)
    filtered_text =[]
    for text in doc:
        if(text.is_stop or text.is_punct):
            continue
        filtered_text.append(text.lemma)
    return wv.get_mean_vector(filtered_text)

In [33]:
v =preprocess("Hi this is nitish")
v.shape

(300,)

In [36]:
df['vector_num'] = df['Text'].apply(lambda text: preprocess(text))
df.head()

,Text,label,label_num,vector_num
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,U.S. conservative leader optimistic of common ...,Real,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,Democrats say Trump agrees to work on immigrat...,Real,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [ ]:
from sklear.model_selection import train_test_split

x_train,y_train